Task_1_2_1
andrey-dru-me1/oop pull request #2
Opened 2022-09-27 13:07 UTC by andrey-dru-me1

2022-10-05 07:02 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +public class Stack<T> {
Нужен базовый пакет

2022-10-05 07:02 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +     * Appends element to the ecd of stack.
end?

2022-10-05 07:02 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length + 1);
Зачем каждый раз перекопировать массив?

2022-10-05 07:02 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length - 1);
Зачем каждый раз перекопировать массив?

2022-10-05 07:03 UTC, molo4evan requested changes
Я не приму PR по ветке, коммиты в которой снабжены сообщением "W". Сообщение коммита должно отражать изменения, которые были в нем произведены.

2022-10-05 08:00 UTC, andrey-dru-me1 commented
> Я не приму PR по ветке, коммиты в которой снабжены сообщением "W". Сообщение коммита должно отражать изменения, которые были в нем произведены.

А что нужно сделать, чтобы это исправить? Коммиты же нельзя переименовывать вроде?
И у меня, кажется, нет коммитов "W"

2022-10-05 08:26 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length + 1);
Я использовал это решение чтобы размер массива всегда был равен количеству элементов. Поскольку в джаве (как и в си) нельзя изменить размер уже существующего массива, то этой строкой я создаю новый массив (из возвращаемого значения `Arrays.copyOf()` ) с необходимым количеством элементов и копирую в него данные со старого массива.

2022-10-05 08:35 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length + 1);
Или требуется написать реализацию вектора со значениями `capacity` и `size` и при достижении предела массива - увеличивать его в два раза?

2022-10-05 08:35 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +     * Appends element to the ecd of stack.
Исправил

2022-10-05 08:38 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +public class Stack<T> {
Добавил путь к пакету: https://github.com/andrey-dru-me1/oop/pull/2/commits/ba370a4c1ba878f84bc4d980e073af746b59fb9b

2022-10-08 20:28 UTC, molo4evan commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length + 1);
Да, хотелось бы видеть что-то подобное. Условный resize factor - это самый оптимальный подход, а создавать новый массив **каждый раз** - сильный оверхед

2022-10-08 20:31 UTC, molo4evan reviewed
Комменты про копирование массива при каждом push и pop все еще актуальны

2022-10-09 03:16 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length + 1);
Исправлено: https://github.com/andrey-dru-me1/oop/pull/2/commits/94f488a66cad2fcf0ad056b311a45272b60aef56

2022-10-09 03:16 UTC, andrey-dru-me1 commented on Task_1_2_1/src/main/java/Stack.java
> +        stack = Arrays.copyOf(stack, stack.length - 1);
Исправлено: https://github.com/andrey-dru-me1/oop/pull/2/commits/94f488a66cad2fcf0ad056b311a45272b60aef56

2022-10-16 16:18 UTC, merged